global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['claim-service:8080', 'policyholder-service:8081', 'notification-service:8082']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
